# To prevent "Warning: Homebrew's sbin was not found in your PATH"
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"

# BEGIN ANSIBLE MANAGED BLOCK: base
HOMEBREW_PREFIX=$(brew --prefix)

# Initialize the completion system
autoload -Uz compinit

# Cache completion if nothing changed - faster startup time
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi

# Enhanced form of menu completion called `menu selection'
zmodload -i zsh/complist

# Load custom aliases dynamically
for alias_file in "${HOME}/Code/ImaginateScata/github.com/dotfiles/cfg/aliases/aliases"*".zsh"; do
    source "${alias_file}"
done

# Load custom integrations dynamically
for integrations_file in "${HOME}/Code/ImaginateScata/github.com/dotfiles/cfg/integration/"*".zsh"; do
    source "${integrations_file}"
done

if [ -f "${HOMEBREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then source "${HOMEBREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"; fi
if [ -f "${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then source "${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"; fi

export STARSHIP_CONFIG=${HOME}/Code/ImaginateScata/github.com/dotfiles/cfg/starship/config.toml
eval "$(starship init zsh)"

# Created by `pipx` on 2021-12-14 08:28:36
export PATH="$PATH:${HOME}/Library/Python/3.9/bin"

# Created by `pipx` on 2021-12-14 08:28:36
export PATH="$PATH:${HOME}/.local/bin"
